# Gradle Arguments
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1
minecraft_version_range=[26.1,]
neo_version=26.1.1.1-beta

## Mod Properties
mod_id=scalar_core
mod_name=Scalar Core
mod_license=GNU General Public License v3 (GPLv3)
mod_version=26.1.1-1.1.0
mod_group_id=dev.lemonjuice.scalar_core
